package model;

import java.util.Date;

public class Employee_Working {
	private String EMPLOYMENT_ID;
	private Date HIRE_DATE_FOR_WORKING;
	private String WORKERS_COMP_CODE;
	private Date TERMINATION_DATE;
	private Date REHIRE_DATE_FOR_WORKING;
	private Date LAST_REVIEW_DATE;
	private int  NUMBER_DAYS_REQUIREMENT_OF_WORKING_PER_MONTH;
	private int NUMBER_DAYS_ACTUAL_OF_WORKING_PER_MONTH;
	private int TOTAL_NUMBER_VACATION_WORKING_DAYS_PER_MONTH;
	public Employee_Working() {
		super();
		// TODO Auto-generated constructor stub
	}
	public Employee_Working(String eMPLOYMENT_ID, Date hIRE_DATE_FOR_WORKING, String wORKERS_COMP_CODE,
			Date tERMINATION_DATE, Date rEHIRE_DATE_FOR_WORKING, Date lAST_REVIEW_DATE,
			int nUMBER_DAYS_REQUIREMENT_OF_WORKING_PER_MONTH, int nUMBER_DAYS_ACTUAL_OF_WORKING_PER_MONTH,
			int tOTAL_NUMBER_VACATION_WORKING_DAYS_PER_MONTH) {
		super();
		EMPLOYMENT_ID = eMPLOYMENT_ID;
		HIRE_DATE_FOR_WORKING = hIRE_DATE_FOR_WORKING;
		WORKERS_COMP_CODE = wORKERS_COMP_CODE;
		TERMINATION_DATE = tERMINATION_DATE;
		REHIRE_DATE_FOR_WORKING = rEHIRE_DATE_FOR_WORKING;
		LAST_REVIEW_DATE = lAST_REVIEW_DATE;
		NUMBER_DAYS_REQUIREMENT_OF_WORKING_PER_MONTH = nUMBER_DAYS_REQUIREMENT_OF_WORKING_PER_MONTH;
		NUMBER_DAYS_ACTUAL_OF_WORKING_PER_MONTH = nUMBER_DAYS_ACTUAL_OF_WORKING_PER_MONTH;
		TOTAL_NUMBER_VACATION_WORKING_DAYS_PER_MONTH = tOTAL_NUMBER_VACATION_WORKING_DAYS_PER_MONTH;
	}
	public String getEMPLOYMENT_ID() {
		return EMPLOYMENT_ID;
	}
	public void setEMPLOYMENT_ID(String eMPLOYMENT_ID) {
		EMPLOYMENT_ID = eMPLOYMENT_ID;
	}
	public Date getHIRE_DATE_FOR_WORKING() {
		return HIRE_DATE_FOR_WORKING;
	}
	public void setHIRE_DATE_FOR_WORKING(Date hIRE_DATE_FOR_WORKING) {
		HIRE_DATE_FOR_WORKING = hIRE_DATE_FOR_WORKING;
	}
	public String getWORKERS_COMP_CODE() {
		return WORKERS_COMP_CODE;
	}
	public void setWORKERS_COMP_CODE(String wORKERS_COMP_CODE) {
		WORKERS_COMP_CODE = wORKERS_COMP_CODE;
	}
	public Date getTERMINATION_DATE() {
		return TERMINATION_DATE;
	}
	public void setTERMINATION_DATE(Date tERMINATION_DATE) {
		TERMINATION_DATE = tERMINATION_DATE;
	}
	public Date getREHIRE_DATE_FOR_WORKING() {
		return REHIRE_DATE_FOR_WORKING;
	}
	public void setREHIRE_DATE_FOR_WORKING(Date rEHIRE_DATE_FOR_WORKING) {
		REHIRE_DATE_FOR_WORKING = rEHIRE_DATE_FOR_WORKING;
	}
	public Date getLAST_REVIEW_DATE() {
		return LAST_REVIEW_DATE;
	}
	public void setLAST_REVIEW_DATE(Date lAST_REVIEW_DATE) {
		LAST_REVIEW_DATE = lAST_REVIEW_DATE;
	}
	public int getNUMBER_DAYS_REQUIREMENT_OF_WORKING_PER_MONTH() {
		return NUMBER_DAYS_REQUIREMENT_OF_WORKING_PER_MONTH;
	}
	public void setNUMBER_DAYS_REQUIREMENT_OF_WORKING_PER_MONTH(int nUMBER_DAYS_REQUIREMENT_OF_WORKING_PER_MONTH) {
		NUMBER_DAYS_REQUIREMENT_OF_WORKING_PER_MONTH = nUMBER_DAYS_REQUIREMENT_OF_WORKING_PER_MONTH;
	}
	public int getNUMBER_DAYS_ACTUAL_OF_WORKING_PER_MONTH() {
		return NUMBER_DAYS_ACTUAL_OF_WORKING_PER_MONTH;
	}
	public void setNUMBER_DAYS_ACTUAL_OF_WORKING_PER_MONTH(int nUMBER_DAYS_ACTUAL_OF_WORKING_PER_MONTH) {
		NUMBER_DAYS_ACTUAL_OF_WORKING_PER_MONTH = nUMBER_DAYS_ACTUAL_OF_WORKING_PER_MONTH;
	}
	public int getTOTAL_NUMBER_VACATION_WORKING_DAYS_PER_MONTH() {
		return TOTAL_NUMBER_VACATION_WORKING_DAYS_PER_MONTH;
	}
	public void setTOTAL_NUMBER_VACATION_WORKING_DAYS_PER_MONTH(int tOTAL_NUMBER_VACATION_WORKING_DAYS_PER_MONTH) {
		TOTAL_NUMBER_VACATION_WORKING_DAYS_PER_MONTH = tOTAL_NUMBER_VACATION_WORKING_DAYS_PER_MONTH;
	}
	
	
	
} 
